
#### Integrations

##### Recorded Future RiskList Feed

- Fixed an issue where in some cases, a "file is already closed" error would be raised.
- Fixed an issue where in some cases, a "TypeError: '<=' not supported between instances of int and NoneType" error would be raised.
- Updated the Docker image to: *demisto/python3:3.10.13.89009*.
